apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-uwsgi
  name: nginx-uwsgi
spec:
  ports:
  - port: 80
    name: port1
    protocol: TCP
    targetPort: 80
    nodePort: 80
  - port: 81
    name: port2
    protocol: TCP
    targetPort: 81
    nodePort: 81
  selector:
    app: nginx-uwsgi
  type: NodePort
status:
  loadBalancer: {}
