# Generated by Django 2.2.23 on 2022-02-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='昵称'),
        ),
    ]
