# Generated by Django 2.2.23 on 2022-03-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.TextField(blank=True, max_length=1000, verbose_name='封面'),
        ),
    ]
